### PR TITLE
Added the name of the author and a link to their site underneath each ar...

### PR DESCRIPTION
**Pull request by emashliles**
...ticle on /blogs

I think I am doing pull requests right?

### CODE REVIEW

**Comment by DannyBrown-xx** [comment]
@emashliles Thanks for the contribution.

@robcrocombe Is currently working on the theming side of the project. I'm not really in any position to say if the code is in the right place etc., So I'll get him to confirm its ok before I pull!

Nice work though! And your pull request worked perfectly.

**Comment by emashliles** [comment]
Awesome - Just wanted to sync a fork with master too. My first ever PR for/from "strangers" :D

**Comment by robcrocombe** [comment]
Hi. I think the direction should be that the user's info is next to their blog post (at least on desktop view), as we're representing them as much as their content. I'll be working on this soon, hopefully. So this might not be the right thing to pull at the moment.

**Comment by DannyBrown-xx** [comment]
As Rob said. @emashliles We appreciate your contribution though. Please tweet me if you want to work on something else? :)

**Pull request closed without merging**
